server:
  port: ${BACK_PORT}
spring:
  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: '10000'
      maximum-pool-size: '5'
      minimum-idle: '3'
    username: ${DB_USER}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useTimezone=true&serverTimezone=UTC&useLegacyDate
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
    database: postgresql
    show-sql: 'false'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

logging:
  level:
    org:
      hibernate: info
      springframework: info
    web: info